name: Redwood
favicon: null
layout_spectrum: 0.7776
typography_spectrum: 0.3727932018227875
title: Redwood Seniors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5ea8b0'
    - '#e7dddb'
    - '#162743'
    - '#6d0019'
    - '#cf2741'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.3790817130357027
  rhythmicContrast: 0.841265578288585
purpose: []
