name: Redwood
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3727932018227875
title: Redwood Seniors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151311'
    - '#4c463c'
    - '#cb957b'
    - '#a46b5a'
    - '#e8c4af'
  brandStrength: 0.42293614242225885
  lightness: 0.4375
  saturation: 0.3790817130357027
  rhythmicContrast: 0.841265578288585
purpose: []
